In [18]:
import pandas as pd

filename1 = 'online_retail_data1.csv'
filename2 = 'online_retail_data2.csv'

def read_data(filename1, filename2):
    """
    Read the dataframes from the given CSV files and return them as a tuple.

    Parameters:
        filename1 (str): CSV file 1
        filename2 (str): CSV file 2

    Returns:
        tuple: (dataframe1, dataframe2)
    """
    dataframe1 = pd.read_csv(filename1)
    dataframe2 = pd.read_csv(filename2)
    return (dataframe1, dataframe2)

def merge_dataframes(df1, df2):
    """
    Merge the two dataframes given in the parameter and return the merged dataframe.

    Parameters:
        df1 (DataFrame): Dataframe 1
        df2 (DataFrame): Dataframe 2

    Returns:
        DataFrame: Merged dataframe
    """
    merged_dataframe = pd.merge(df1, df2, how='outer')
    return merged_dataframe

def split_datetime(dataframe):
    """
    Split 'InvoiceDate' column and save the date and time values separately to 'date' and 'time' columns.

    Parameters:
        dataframe (DataFrame): Input dataframe

    Returns:
        DataFrame: Modified dataframe
    """
    dataframe['date'] = pd.to_datetime(dataframe['InvoiceDate']).dt.date
    dataframe['time'] = pd.to_datetime(dataframe['InvoiceDate']).dt.time
    return dataframe

def avg_price(dataframe):
    """
    Get the average of each country's average UnitPrice.

    Parameters:
        dataframe (DataFrame): Input dataframe

    Returns:
        Series: Series sorted in descending order by the average UnitPrice
    """
    avg_unitprice = dataframe.groupby('Country')['UnitPrice'].mean().sort_values(ascending=False)
    return avg_unitprice

def convert_datetime(dataframe):
    """
    Convert 'InvoiceDate' column to datetime and format it to a specific format.

    Parameters:
        dataframe (DataFrame): Input dataframe

    Returns:
        DataFrame: Modified dataframe with a new 'InvoiceDate_Format' column
    """
    dataframe['InvoiceDate'] = pd.to_datetime(dataframe['InvoiceDate']).dt.strftime('%d/%m/%Y')
    return dataframe

def purchase_made(dataframe):
    """
    Create a new column 'TimeOfDay' and fill it values based on the specified conditions.

    Parameters:
        dataframe (DataFrame): Input dataframe

    Returns:
        DataFrame: Modified dataframe
    """
    # Assuming that 'time' column exists in the dataframe (created by split_datetime function)
    dataframe['TimeOfDay'] = dataframe['time'].apply(lambda x: 'Morning' if 7 <= x.hour <= 15 else ('Evening' if 16 <= x.hour <= 18 else ('Night' if 19 <= x.hour <= 20 else 'Other')))
    return dataframe

def get_timeoftheday(dataframe):
    """
    Write a function to perform the below tasks
    1. create a new column called 'year' and fill it with years from 'InvoiceDate' column.
    2. groupby using year and Timeoftheday.
    Note:
        output should be in this format
        TimeOfDay	Evening	Morning	Night
            year			
            2010	value	value	value
            2011	value	value	value
    Input:
        dataframe - DataFrame
    Output:
        DataFrame
    """
    # Step 1: Create a new column 'year' and fill it with years from 'InvoiceDate' column
    dataframe['year'] = pd.to_datetime(dataframe['InvoiceDate'], format='%d/%m/%Y').dt.year

    # Step 2: Groupby using year and TimeOfDay, and calculate the count (you can use any other aggregation function if needed)
    grouped_df = dataframe.groupby(['year', 'TimeOfDay']).size().unstack(fill_value=0)

    return grouped_df

In [19]:
filename1 = 'online_retail_data1.csv'
filename2 = 'online_retail_data2.csv'
df1, df2 = read_data(filename1, filename2)
merged_df = merge_dataframes(df1, df2)
modified_df = split_datetime(merged_df)
average_prices = avg_price(modified_df)
converted_df = convert_datetime(modified_df)
final_df = purchase_made(converted_df)
result_df = get_timeoftheday(final_df)

In [20]:
result_df

TimeOfDay  Evening  Morning  Night
year
2010          6290    35746    445
2011          9003    48337    179